YamanakaRails/reservation-chap9/config/routes.rb
Rails.application.routes.draw do
#  get 'entries/index'
#  get 'entries/new'
#  get 'entries/confirm'
#  get 'entries/create'
#  get 'entries/destroy'
  root "top#index"
  resources :rooms

  resources :entries, only: [:new, :create, :destroy, :index], path: :rentals do
    post :confirm, on: :collection
  end
end

YamanakaRails/reservation-chap9/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

YamanakaRails/reservation-chap9/app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :room

    scope :least_entries, ->(base_date) {
        where("reserved_date >= ? and reserved_date <= ?",
            base_date.to_date - 7.days, base_date.to_date + 7.days )
    }
end

YamanakaRails/reservation-chap9/app/models/room.rb
class Room < ApplicationRecord
    has_many :entries, dependent: :destroy

    validates :name, :place, :number, presence: true
    validates :name, length: {maximum: 30}
    validates :place, inclusion: { in: ['東京', '大阪', '福岡', '札幌', '仙台', '名古屋', '金沢']}
    validates :number, numericality: { greater_than: 4, less_than: 31 }
    validate :name_format
    validate :check_x5
    before_validation :space_edit

    private
    
    def name_format
        name_pattern = /\A.+#\d{2}\z/
        unless name_pattern.match(self.name)
            errors.add(:name, "会議室名が正しくありません")
        end
    end

    def check_x5
        if (self.number.to_i % 5) != 0
            errors.add(:number, "収容人数は5の倍数で指定してください")
        end
    end

    def space_edit
        self.name = self.name.strip.gsub(/ +/, "_")
    end
end

YamanakaRails/reservation-chap9/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    USERS = { "admin_user" => "admin_password" }
    before_action :authenticate

private
    def authenticate
        authenticate_or_request_with_http_digest do |username|
            USERS[username]
        end
    end
end

YamanakaRails/reservation-chap9/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:destroy]

  def index
    @entries = Entry.all
  end

  def new
    @entry = Entry.new
  end

  def confirm
  end

  def create
    @entry = Entry.new(entry_params)
    respond_to to do |format| 
      if @entry.save
        format.html { redirect_to @entry, notice: '予算完了' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: '予約解除完了' }
    end
  end

private
  def set_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:user_name, :user_email, :reserved_date, :usage_time, :room_id, :people)
  end
end

YamanakaRails/reservation-chap9/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        session[:room] = @room.name
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :place, :number)
    end
end

YamanakaRails/reservation-chap9/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    # TODO: todoテスト
  end
end

YamanakaRails/reservation-chap9/app/helpers/application_helper.rb
module ApplicationHelper
end

YamanakaRails/reservation-chap9/app/helpers/entries_helper.rb
module EntriesHelper
end

YamanakaRails/reservation-chap9/app/helpers/rooms_helper.rb
module RoomsHelper
end

YamanakaRails/reservation-chap9/app/helpers/top_helper.rb
module TopHelper
end

YamanakaRails/reservation-chap9/app/views/entries/confirm.html.erb
<h1>Entries#confirm</h1>
<p>Find me in app/views/entries/confirm.html.erb</p>

YamanakaRails/reservation-chap9/app/views/entries/create.html.erb
<h1>Entries#create</h1>
<p>Find me in app/views/entries/create.html.erb</p>

YamanakaRails/reservation-chap9/app/views/entries/destroy.html.erb
<h1>Entries#destroy</h1>
<p>Find me in app/views/entries/destroy.html.erb</p>

YamanakaRails/reservation-chap9/app/views/entries/index.html.erb
<h1>Entries#index</h1>
<p>Find me in app/views/entries/index.html.erb</p>

YamanakaRails/reservation-chap9/app/views/entries/new.html.erb
<h1>Entries#new</h1>
<p>Find me in app/views/entries/new.html.erb</p>

YamanakaRails/reservation-chap9/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

YamanakaRails/reservation-chap9/app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :place, style: "display: block" %>
    <%= form.text_field :place %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

YamanakaRails/reservation-chap9/app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Name:</strong>
    <%= room.name %>
  </p>

  <p>
    <strong>Place:</strong>
    <%= room.place %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= room.number %>
  </p>

</div>

YamanakaRails/reservation-chap9/app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

YamanakaRails/reservation-chap9/app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>
<%= "最近登録の部屋は、#{session[:room]}です。" if session[:room] %>
<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>list
      <%= link_to "Show this room", room %>
    </p>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

YamanakaRails/reservation-chap9/app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

YamanakaRails/reservation-chap9/app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>

YamanakaRails/reservation-chap9/app/views/top/index.html.erb
<h1>予約管理のページへ　ようこそ</h1>
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>